name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: apt install libopencv-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
